defaults:
  - _self_
  - client: user
  - therapist: CBT
  - evaluator: basic
session:
  lang: en
  reminder_turn_num: 5
  max_turns: 10
  langfuse: False
  recursion_limit: 1000
  output_dir: "data/sessions/dify/session_1.json"